version: '3.6'

services:
  traefik:
    image: traefik:latest
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=mycachebot@gmail.com"
      #- "--certificatesresolvers.myhttpchallenge.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.proxy.loadbalancer.server.port=9999"
        # global redirect to https
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
        # middleware redirect
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "letsencrypt:/letsencrypt/"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: traefik
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
          #- "traefik.http.routers.frontend.entrypoints=web"
          - "traefik.http.routers.frontend.entrypoints=websecure"
          - "traefik.http.routers.frontend.tls.certresolver=myhttpchallenge"
          - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
